##Micronaut
micronaut:
  application:
    name: tecSale
  server:
    cors:
      enabled: true
    port: 8081
endpoints:
  health:
    enabled: true

#Cassandra
cassandra:
  default:
    advanced:
      metadata:
        schema:
          enabled: false
    basic:
      contact-points:
        - "127.17.0.2:9042"
      port: 9042
      load-balancing-policy:
        local-datacenter: datacenter1